In [60]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.3f}'.format

In [42]:
df_res = pd.read_csv('res.csv')

models = df_res['Modelo'].unique()
n_models = len(models)

In [61]:
bias_gow = np.array([df_res[df_res['Modelo'] == model]['bias_gow'] for model in models])
bias_gow.T

array([[-0.08938559,  0.0213152 ,  0.03148082,  0.07625981, -0.0108293 ,
         0.03106692],
       [-0.31402948, -0.05454797,  0.01767921, -0.03787713, -0.05479422,
         0.01503391],
       [ 0.06599839, -0.01031965,  0.02677716, -0.05928524, -0.01210735,
         0.03597519],
       [ 0.10084054,  0.06706872,  0.12476763,  0.10361052, -0.01892312,
         0.12893012],
       [-0.01728524,  0.09096445,  0.1252987 ,  0.14234431,  0.01015554,
         0.13105005],
       [-0.08745448, -0.16640304, -0.00534809,  0.01260067, -0.01304859,
         0.00278076],
       [-0.13860333, -0.06197715, -0.02657934,  0.022425  , -0.04172361,
        -0.02926881],
       [-0.0876856 , -0.065241  ,  0.04646308,  0.04037978, -0.01988199,
         0.05142097],
       [-0.33922121, -0.15762609,  0.04117343,  0.06539406, -0.0130802 ,
         0.06831158],
       [-0.18074653, -0.09782589,  0.03344907,  0.02970003, -0.01488862,
         0.03882635],
       [-0.2399118 ,  0.19350055,  0.21400716,  0.

In [62]:
bias_cop = np.array([df_res[df_res['Modelo'] == model]['bias_cop'] for model in models])
bias_cop.T

array([[-0.30012687, -0.09518812, -0.01674394, -0.12988541, -0.03602503,
        -0.00332548],
       [-0.15791212, -0.26270358, -0.06761056, -0.17153484, -0.04655528,
        -0.0789311 ],
       [-0.1935608 , -0.25817423, -0.09090937, -0.15732105, -0.04469075,
        -0.10019923],
       [-0.17721481, -0.159846  , -0.01531236, -0.04892103, -0.03075548,
        -0.01847176],
       [-0.21410297, -0.07111427, -0.03125718, -0.04581297, -0.0376487 ,
        -0.0283116 ],
       [-0.29591731, -0.3379142 ,  0.00827453, -0.0092935 , -0.04734115,
         0.04194544],
       [-0.49542685, -0.19254704,  0.00968899, -0.00670396, -0.02414353,
         0.02242736],
       [-0.43703433, -0.26314191,  0.01134791, -0.02811109, -0.03717979,
         0.0160393 ],
       [-0.53037099, -0.29663405,  0.03559838,  0.03445044, -0.04419237,
         0.0614459 ],
       [-0.4982406 , -0.34898694, -0.02387976, -0.03508464, -0.05263128,
        -0.03120174],
       [-0.65378427, -0.20640867, -0.00752498,  0.

In [52]:
rmse_gow = np.array([df_res[df_res['Modelo'] == model]['rmse_gow'] for model in models])
rmse_gow.T

array([[0.35539589, 0.37967091, 0.38026724, 0.39443354, 0.37343463,
        0.37657068],
       [0.5071074 , 0.42175458, 0.41926985, 0.4239186 , 0.40982256,
        0.39703774],
       [0.38199248, 0.39816993, 0.39913507, 0.43827527, 0.40404144,
        0.41195128],
       [0.40955134, 0.41071445, 0.42181697, 0.43187985, 0.39706864,
        0.42774537],
       [0.36284912, 0.41852149, 0.42491481, 0.42543812, 0.37271458,
        0.42048365],
       [0.27255681, 0.30496957, 0.25577197, 0.24454336, 0.23992595,
        0.24292552],
       [0.33096707, 0.29287536, 0.28711075, 0.27869834, 0.28586584,
        0.28675065],
       [0.26652268, 0.27366495, 0.27188799, 0.29455376, 0.26652077,
        0.27566549],
       [0.45337906, 0.34264812, 0.31185892, 0.27875249, 0.26145893,
        0.27504513],
       [0.30448561, 0.26229946, 0.243711  , 0.24264825, 0.22595405,
        0.23239854],
       [0.45854939, 0.39773208, 0.40319704, 0.4395773 , 0.31770176,
        0.45778599],
       [0.40258842, 0

In [53]:
rmse_cop = np.array([df_res[df_res['Modelo'] == model]['rmse_cop'] for model in models])
rmse_cop.T

array([[0.47884476, 0.38349529, 0.37273362, 0.40837597, 0.36838526,
        0.36850767],
       [0.38362169, 0.44879001, 0.37322913, 0.38138624, 0.34410471,
        0.36207603],
       [0.44279033, 0.48707212, 0.42304424, 0.42733278, 0.39496583,
        0.40746424],
       [0.41771815, 0.42789086, 0.39547943, 0.3963566 , 0.38406369,
        0.38307292],
       [0.40230674, 0.36437872, 0.3585397 , 0.36974551, 0.35777381,
        0.36059171],
       [0.45748906, 0.48035147, 0.34452454, 0.29619994, 0.29279014,
        0.28396936],
       [0.63782222, 0.40355409, 0.35877368, 0.31937855, 0.30139896,
        0.30015513],
       [0.53006864, 0.39196905, 0.29666495, 0.30772123, 0.28049001,
        0.27833885],
       [0.62615621, 0.40548992, 0.29696932, 0.31982528, 0.27382001,
        0.2880905 ],
       [0.59616672, 0.45593636, 0.29621142, 0.29772013, 0.28023393,
        0.28303689],
       [0.86174898, 0.46674426, 0.42285195, 0.42951031, 0.41418923,
        0.41483745],
       [0.64849634, 0

In [56]:
p_gow = np.array([df_res[df_res['Modelo'] == model]['pearson_gow'] for model in models])
p_gow.T

array([[0.95927363, 0.95779025, 0.95779069, 0.95856256, 0.95828688,
        0.95855753],
       [0.94486757, 0.94384987, 0.94382194, 0.94357762, 0.94727854,
        0.9496268 ],
       [0.96080742, 0.96251984, 0.9625051 , 0.95671615, 0.96139367,
        0.96021205],
       [0.95390645, 0.95631346, 0.95641988, 0.95468189, 0.95718238,
        0.95633596],
       [0.96179821, 0.96068282, 0.96069289, 0.96315156, 0.96335108,
        0.96308384],
       [0.92329963, 0.92477664, 0.92492715, 0.9349421 , 0.93259331,
        0.93289726],
       [0.91238689, 0.92540549, 0.92507757, 0.92983507, 0.92618205,
        0.925564  ],
       [0.91610084, 0.90970856, 0.90856806, 0.90209616, 0.90918603,
        0.90615207],
       [0.82500346, 0.80696485, 0.80194924, 0.87946846, 0.857968  ,
        0.86106728],
       [0.90956626, 0.91609592, 0.91705432, 0.93107573, 0.92738463,
        0.92707237],
       [0.93546589, 0.95591737, 0.95578199, 0.9554078 , 0.95217468,
        0.94882298],
       [0.92236306, 0

In [57]:
p_cop = np.array([df_res[df_res['Modelo'] == model]['pearson_cop'] for model in models])
p_cop.T

array([[0.95776054, 0.95868793, 0.95853775, 0.95874812, 0.95990574,
        0.95936681],
       [0.95171256, 0.95964644, 0.95901418, 0.96344302, 0.96344655,
        0.9619183 ],
       [0.95526434, 0.96036507, 0.96040417, 0.96334695, 0.96381361,
        0.96376076],
       [0.95602585, 0.95705679, 0.95739827, 0.95944166, 0.96040907,
        0.96011988],
       [0.96767529, 0.96640078, 0.96643441, 0.96618902, 0.96671307,
        0.96600531],
       [0.84672932, 0.85774235, 0.85539174, 0.90565202, 0.90082186,
        0.90634593],
       [0.88184268, 0.88055782, 0.87780365, 0.91459605, 0.91616075,
        0.91693868],
       [0.89869606, 0.8904344 , 0.88604216, 0.89459634, 0.9001984 ,
        0.90034543],
       [0.82730416, 0.83908135, 0.81717195, 0.83574443, 0.84551105,
        0.83972693],
       [0.86477186, 0.87297685, 0.87123261, 0.8853107 , 0.88938347,
        0.8854073 ],
       [0.91134944, 0.91388039, 0.91270376, 0.91538994, 0.91929836,
        0.91624131],
       [0.89045191, 0

In [58]:
si_gow = np.array([df_res[df_res['Modelo'] == model]['si_gow'] for model in models])
si_gow.T

array([[0.18430248, 0.18560782, 0.18589935, 0.19282475, 0.18255912,
        0.18409223],
       [0.25033693, 0.19653919, 0.1953813 , 0.19754763, 0.19097882,
        0.18502105],
       [0.15437431, 0.15253838, 0.15290812, 0.16790268, 0.15478775,
        0.157818  ],
       [0.16212507, 0.15406204, 0.15822668, 0.16200134, 0.14894339,
        0.16045047],
       [0.15123196, 0.16482475, 0.1673426 , 0.1675487 , 0.14678478,
        0.1655975 ],
       [0.22391637, 0.24289629, 0.20371233, 0.19476919, 0.1910916 ,
        0.19348064],
       [0.32416757, 0.28636895, 0.2807324 , 0.27250688, 0.27951515,
        0.2803803 ],
       [0.26106712, 0.27158397, 0.26982051, 0.29231393, 0.26449409,
        0.27356929],
       [0.55026984, 0.42564982, 0.38740239, 0.34627638, 0.3247937 ,
        0.34167096],
       [0.34313923, 0.29883585, 0.27765815, 0.27644736, 0.25742779,
        0.26476994],
       [0.34975029, 0.30241222, 0.30656746, 0.33422888, 0.24156185,
        0.34807371],
       [0.37513233, 0

In [59]:
si_cop = np.array([df_res[df_res['Modelo'] == model]['si_cop'] for model in models])
si_cop.T

array([[0.24832104, 0.18747743, 0.18221642, 0.19964072, 0.18009066,
        0.1801505 ],
       [0.18937739, 0.2091378 , 0.17392615, 0.1777274 , 0.16035406,
        0.16872876],
       [0.1789445 , 0.18659669, 0.1620677 , 0.16371063, 0.15131089,
        0.15609902],
       [0.16535799, 0.16050504, 0.14834727, 0.1486763 , 0.14406514,
        0.1436935 ],
       [0.16767751, 0.14350191, 0.14120235, 0.14561549, 0.14090072,
        0.14201048],
       [0.37584564, 0.38258108, 0.27440027, 0.23591162, 0.23319585,
        0.22617045],
       [0.62471858, 0.39458888, 0.35080329, 0.31228335, 0.29470319,
        0.29348699],
       [0.51921844, 0.38898847, 0.29440907, 0.30538127, 0.27835712,
        0.27622232],
       [0.7599709 , 0.5037142 , 0.36890599, 0.39729848, 0.34014907,
        0.35787639],
       [0.67184846, 0.51944494, 0.33747149, 0.33919035, 0.31926845,
        0.32246184],
       [0.65728353, 0.35488505, 0.32151191, 0.32657453, 0.31492528,
        0.31541814],
       [0.6042696 , 0

In [46]:
print((bias_gow.mean(axis=1)+bias_cop.mean(axis=1))/2)
print((bias_gow.std(axis=1)+bias_cop.std(axis=1))/2)

[-0.2376035  -0.12146692  0.02114574  0.01339671 -0.02693292  0.0285409 ]
[0.14545107 0.08903436 0.04586169 0.06770004 0.01804414 0.05271825]


In [48]:
print((rmse_gow.mean(axis=1)+rmse_cop.mean(axis=1))/2)
print((rmse_gow.std(axis=1)+rmse_cop.std(axis=1))/2)

[0.43588658 0.37087567 0.33463068 0.33653484 0.31424192 0.32413923]
[0.11417692 0.06591451 0.06452779 0.0717336  0.06408943 0.07003003]


In [47]:
print((p_gow.mean(axis=1)+p_cop.mean(axis=1))/2)
print((p_gow.std(axis=1)+p_cop.std(axis=1))/2)

[0.91137214 0.91465294 0.9136273  0.92504997 0.92471478 0.92467705]
[0.0494499  0.05039058 0.05147875 0.03773386 0.03876124 0.03872722]


In [49]:
print((si_gow.mean(axis=1)+si_cop.mean(axis=1))/2)
print((si_gow.std(axis=1)+si_cop.std(axis=1))/2)

[0.33978456 0.27446846 0.24205518 0.24129483 0.22540949 0.23219543]
[0.1593252  0.09924194 0.07396071 0.07040424 0.06384257 0.06814608]
