In [26]:
import pandas as pd
import numpy as np
pd.options.display.float_format = '{:.2f}'.format

In [38]:
df_res = pd.read_csv('res_raw.csv')

models = df_res['Modelo'].unique()
n_models = len(models)

In [39]:
bias_gow = np.array([df_res[df_res['Modelo'] == model]['bias_gow'] for model in models])
bias_cop = np.array([df_res[df_res['Modelo'] == model]['bias_cop'] for model in models])
rmse_gow = np.array([df_res[df_res['Modelo'] == model]['rmse_gow'] for model in models])
rmse_cop = np.array([df_res[df_res['Modelo'] == model]['rmse_cop'] for model in models])
p_gow = np.array([df_res[df_res['Modelo'] == model]['pearson_gow'] for model in models])
p_cop = np.array([df_res[df_res['Modelo'] == model]['pearson_cop'] for model in models])
si_gow = np.array([df_res[df_res['Modelo'] == model]['si_gow'] for model in models])
si_cop = np.array([df_res[df_res['Modelo'] == model]['si_cop'] for model in models])

In [37]:
bias_gow.T

array([[-0.08938559,  0.0213152 ,  0.03089876,  0.07625981, -0.0108293 ,
         0.03106692],
       [-0.31402948, -0.05454797,  0.00054837, -0.03787713, -0.05479422,
         0.01503391],
       [ 0.06599839, -0.01031965,  0.0268898 , -0.05928524, -0.01210735,
         0.03597519],
       [ 0.10084054,  0.06706872,  0.1242499 ,  0.10361052, -0.01892312,
         0.12893012],
       [-0.01728524,  0.09096445,  0.12324714,  0.14234431,  0.01015554,
         0.13105005],
       [-0.08745448, -0.16640304, -0.01903207,  0.01260067, -0.01304859,
         0.00278076],
       [-0.13860333, -0.06197715, -0.02966373,  0.022425  , -0.04172361,
        -0.02926881],
       [-0.0876856 , -0.065241  ,  0.03486457,  0.04037978, -0.01988199,
         0.05142097],
       [-0.33922121, -0.15762609, -0.02519155,  0.06539406, -0.0130802 ,
         0.06831158],
       [-0.18074653, -0.09782589,  0.00685319,  0.02970003, -0.01488862,
         0.03882635],
       [-0.2399118 ,  0.19350055,  0.20364621,  0.

In [36]:
print((si_gow.mean(axis=1)+si_cop.mean(axis=1))/2)
print((si_gow.std(axis=1)+si_cop.std(axis=1))/2)

[0.33978456 0.27446846 0.24831587 0.24129483 0.22540949 0.23219543]
[0.1593252  0.09924194 0.08001621 0.07040424 0.06384257 0.06814608]
